# Generated by Django 4.2.6 on 2023-10-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_alter_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='description', max_length=800),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default='name', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.TextField(default='login', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default='password', max_length=20),
        ),
    ]
