# Generated by Django 4.2.6 on 2023-10-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0007_user_description_user_name_alter_user_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.TextField(default='id', max_length=20, primary_key=True, serialize=False),
        ),
    ]
