# Generated by Django 4.2.6 on 2023-10-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0010_rename_pic_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='/profilePictures/anonymous.png', upload_to='profilePictures'),
        ),
    ]
