# Generated by Django 4.2.6 on 2023-10-12 14:18

import Tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0011_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='media/anonymous.png', null=True, upload_to=Tasks.models.user_profile_image_path),
        ),
    ]
