# Generated by Django 4.2.6 on 2023-10-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_remove_user_nome_user_name_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.TextField(default='admin', max_length=80, primary_key=True, serialize=False),
        ),
    ]
