# Generated by Django 4.2.6 on 2023-10-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_remove_user_id_remove_user_name_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='name',
        ),
    ]
