# Generated by Django 4.2.6 on 2023-10-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_rename_name_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.TextField(default='admin', max_length=20, primary_key=True, serialize=False),
        ),
    ]
