# Generated by Django 4.2.7 on 2023-11-09 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0024_delete_node_remove_group_adminlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userListNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.user')),
                ('next', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.userlistnode')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.userlistnode')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='groupsList',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.userlistnode'),
        ),
    ]
