# Generated by Django 4.2.7 on 2023-11-09 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0026_alter_user_groupslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedlist',
            name='nodeType',
            field=models.TextField(default='User', max_length=5),
        ),
        migrations.CreateModel(
            name='groupListNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.group')),
                ('next', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.userlistnode')),
            ],
        ),
    ]
