# Generated by Django 4.2.7 on 2023-11-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0031_remove_linkedlist_nodetype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkedList',
            new_name='groupLinkedList',
        ),
        migrations.DeleteModel(
            name='userListNode',
        ),
    ]
