# Generated by Django 4.2.7 on 2023-11-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0037_alter_group_adminlist_alter_group_memberslist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='adminList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='Tasks.userbinarysearchtree'),
        ),
        migrations.AlterField(
            model_name='group',
            name='membersList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Tasks.userbinarysearchtree'),
        ),
        migrations.AlterField(
            model_name='grouplinkedlist',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.grouplistnode'),
        ),
        migrations.AlterField(
            model_name='grouplistnode',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.group'),
        ),
        migrations.AlterField(
            model_name='grouplistnode',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.grouplistnode'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groupsList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.grouplinkedlist'),
        ),
        migrations.AlterField(
            model_name='userbinarysearchtree',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userTree', to='Tasks.usertreenode'),
        ),
        migrations.AlterField(
            model_name='usertreenode',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataTreeNode', to='Tasks.user'),
        ),
        migrations.AlterField(
            model_name='usertreenode',
            name='left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leftData', to='Tasks.usertreenode'),
        ),
        migrations.AlterField(
            model_name='usertreenode',
            name='right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rightData', to='Tasks.usertreenode'),
        ),
    ]
