# Generated by Django 4.2.7 on 2023-12-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0040_remove_usertreenode_state_usertreenode_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertreenode',
            old_name='name',
            new_name='state',
        ),
    ]
