# Generated by Django 4.2.7 on 2023-12-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0041_rename_name_usertreenode_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduleListNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, max_length=50, null=True)),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_node', to='Tasks.schedulelistnode')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_node', to='Tasks.schedulelistnode')),
            ],
        ),
        migrations.CreateModel(
            name='scheduleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.schedulelistnode')),
            ],
        ),
        migrations.AddField(
            model_name='usertreenode',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.schedulelist'),
        ),
    ]
