# Generated by Django 4.2.6 on 2023-10-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_rename_login_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='login',
        ),
    ]
