# Generated by Django 4.2.6 on 2023-10-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0008_remove_user_login_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='/media/profilePictures/anonymous.png', upload_to='profilePictures'),
        ),
    ]
