# Generated by Django 4.2.6 on 2023-10-12 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0009_user_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pic',
            new_name='picture',
        ),
    ]
