# Generated by Django 4.2.6 on 2023-10-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0018_alter_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.TextField(default='pt', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.TextField(default='light', max_length=5),
        ),
    ]
