# Generated by Django 4.2.7 on 2023-11-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0019_user_language_alter_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.TextField(default='name', max_length=80)),
                ('id', models.TextField(default='id', max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(default='description', max_length=800)),
            ],
        ),
    ]
