# Generated by Django 4.2.7 on 2023-11-06 18:51

import Tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0020_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='picture',
            field=models.ImageField(blank=True, default='media/defBanner.png', null=True, upload_to=Tasks.models.group_image_path),
        ),
    ]
