# Generated by Django 4.2.7 on 2023-11-09 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0021_group_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='binarySearchTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='adminList',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.linkedlist'),
        ),
        migrations.AddField(
            model_name='group',
            name='membersList',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.binarysearchtree'),
        ),
        migrations.AddField(
            model_name='user',
            name='groupsList',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.linkedlist'),
        ),
    ]
