# Generated by Django 4.2.7 on 2023-11-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0023_node'),
    ]

    operations = [
        migrations.DeleteModel(
            name='node',
        ),
        migrations.RemoveField(
            model_name='group',
            name='adminList',
        ),
        migrations.RemoveField(
            model_name='group',
            name='membersList',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groupsList',
        ),
        migrations.DeleteModel(
            name='binarySearchTree',
        ),
        migrations.DeleteModel(
            name='LinkedList',
        ),
    ]
