# Generated by Django 4.2.7 on 2023-11-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0027_linkedlist_nodetype_grouplistnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedlist',
            name='nodeType',
            field=models.TextField(default='Group', max_length=5),
        ),
    ]
