# Generated by Django 4.2.7 on 2023-11-10 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0028_alter_linkedlist_nodetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedlist',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.grouplistnode'),
        ),
        migrations.AlterField(
            model_name='linkedlist',
            name='nodeType',
            field=models.TextField(default='User', max_length=5),
        ),
    ]
