# Generated by Django 4.2.7 on 2023-11-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0030_alter_grouplistnode_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedlist',
            name='nodeType',
        ),
    ]
