# Generated by Django 4.2.7 on 2023-11-16 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0032_rename_linkedlist_grouplinkedlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataTreeNode', to='Tasks.user')),
                ('left', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leftData', to='Tasks.usertreenode')),
                ('right', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rightData', to='Tasks.usertreenode')),
            ],
        ),
        migrations.CreateModel(
            name='userBinarySearchTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userTree', to='Tasks.usertreenode')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='adminList',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='Tasks.userbinarysearchtree'),
        ),
        migrations.AddField(
            model_name='group',
            name='membersList',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Tasks.userbinarysearchtree'),
        ),
    ]
