# Generated by Django 4.2.7 on 2023-11-17 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0034_remove_group_adminlist_usertreenode_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertreenode',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataTreeNode', to='Tasks.user'),
        ),
    ]
