# Generated by Django 4.2.7 on 2023-12-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0038_alter_group_adminlist_alter_group_memberslist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertreenode',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
