# Generated by Django 4.2.7 on 2023-12-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0039_usertreenode_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertreenode',
            name='state',
        ),
        migrations.AddField(
            model_name='usertreenode',
            name='name',
            field=models.TextField(default='0', max_length=1),
        ),
    ]
